<tr class="border-2">
    <td class="border-2"><?php echo $row[0] ?></td>
    <td class="border-2"><?php echo $row[1] ?></td>
    <td class="border-2"><?php echo $row[2] ?></td>
    <td class="border-2"><?php echo $row[3] ?></td>
    <td class="border-2"><?php echo $row[4] ?></td>
    <?php
    if ($row[5] != "") echo ('<td class="border-2">
        <form method="GET">
            <input type="hidden" name="page" value="Personalverwaltung" />
            <input type="hidden" name="method" value="UPDATE" />
            <button type="submit">' . $row[5] . '</a>
        </form>
    </td>');

    if ($row[6] != "") echo ('<td class="border-2">
        <form method="GET">
            <input type="hidden" name="page" value="Personalverwaltung" />
            <input type="hidden" name="id" value="' . $row[0] . '" />
            <input type="hidden" name="method" value="DELETE" />
            <button type="submit">' . $row[6] . '</a>
        </form>
    </td>');
    ?>
</tr>